#//////////////////////////////////////////////////////////////////////
#//////////////////////////////////////////////////////////////////////
# ------------------ SLAM Simulation Parameters -----------------------
#//////////////////////////////////////////////////////////////////////
#//////////////////////////////////////////////////////////////////////


# Desired framerate
numberOfClouds : 6

# FileName and absolute path
baseName: Scan
fileLocation: /home/karrer/BoilerScanning/BOILER_8055_1027_144138/Scans/PTS_Data/
